import Head from 'next/head';
import Main from '../components/main/Main';
import HomePageLayout from '../components/main/HomePageLayout';
import Relevant from './relevant';

export default function Index() {
  return (
    <div className='bg-black'>
      <Head>
        <title>DEVS Community 👩‍💻👨‍💻</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon-32x32.png' />
      </Head>
      <Relevant />
    </div>
  );
}

Index.getLayout = function getLayout(page) {
  return (
    <Main>
      <HomePageLayout>{page}</HomePageLayout>
    </Main>
  );
};
