import Head from 'next/head';
import Main from '../components/main/Main';
import dynamic from 'next/dynamic';
import Layout1 from '../components/main/Layout1';






const DynamicComponent = dynamic(() => import('./[sortby]'), { loading: () => <p>loading...</p> });
export default function Index() {
  
 
 

  return (
    <div>
      <Head>
        <title>DEVS Community 👩‍💻👨‍💻</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon-32x32.png' />
      </Head>
      <DynamicComponent /> 
  
    </div>
  );
}

Index.getLayout = function getLayout(page) {
 
  return (
   <Main><Layout1>{page}</Layout1></Main>
  )
}


